### ISSUE TITLE
dev server is not working.

### ISSUE THREAD

**Issue by joyfuI** [dev5c32373043/parcel-reporter-clean-dist#7] opened 2022-01-13 16:14 UTC
If this plugin is added, the dev server will not work.

[https://codesandbox.io/s/parcel-reporter-clean-dist-nz400](https://codesandbox.io/s/parcel-reporter-clean-dist-nz400)

It cannot be checked in the codesandbox, and it is reproduced after downloading it by going to File->Export to ZIP.

It works without this plugin, but does not work if you add it.

**Comment by dev5c32373043** [comment] 2022-01-13 16:23
@joyfuI you need to add a dev-server reporter to the config to make it work.

```
// .parcelrc
{
  "extends": ["@parcel/config-default"],
  "reporters": ["@parcel/reporter-dev-server", "parcel-reporter-clean-dist"] 
}
```

Closing this issue because it is a duplicate of https://github.com/dev5c32373043/parcel-reporter-clean-dist/issues/6

**Closed as completed by dev5c32373043** 2022-01-13 16:23 UTC

**Comment by joyfuI** [comment] 2022-01-13 16:29
thank you. I got a hint from the answer and solved it as follows.
```json
{
  "extends": "@parcel/config-default",
  "reporters": ["parcel-reporter-clean-dist", "..."]
}
```

It would be nice to have that in the README.md.

**Comment by dev5c32373043** [comment] 2022-01-13 16:35
@joyfuI yeah, I'll update README soon
